#include "RendererOpenGL.h"

namespace render
{
	ShaderOpenGL* shaders[MAX_SHADERS];
	ShadowMapPack shadowMapPack;

	// X, Y, U, V
	const float screenQuad[] = 
	{
		-1.0f,  1.0f, 0.0f, 1.0f,
		-1.0f, -1.0f, 0.0f, 0.0f,
		1.0f, -1.0f,  1.0f, 0.0f,

		-1.0f,  1.0f, 0.0f, 1.0f,
		1.0f, -1.0f,  1.0f, 0.0f,
		1.0f,  1.0f,  1.0f, 1.0f
	};

#define UNIT_CUBE 0.5f
	const float unitCubePositions[] =
	{
		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,

		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,

		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,

		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,

		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE,  UNIT_CUBE,
		-UNIT_CUBE,  UNIT_CUBE, -UNIT_CUBE,

		-UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE, -UNIT_CUBE,
		-UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE,
		 UNIT_CUBE, -UNIT_CUBE,  UNIT_CUBE
	};
}